In [2]:
import torch

In [4]:
data=[[1,2],[3,4]]
data1=torch.tensor(data)
print(data1)

tensor([[1, 2],
        [3, 4]])


In [5]:
shape=(2,3)
ones=torch.ones(shape)
zeros=torch.zeros(shape)
random=torch.tensor(shape)
print(ones)
print(zeros)
print(random)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([2, 3])


In [6]:
copy=torch.randn_like(data1,dtype=torch.float)
print(copy)

tensor([[ 0.7766, -0.1226],
        [ 0.7101,  0.4262]])


In [7]:
tensor=torch.rand(2,3)
print(tensor.shape)
print(tensor.device)
print(tensor.dtype)

torch.Size([2, 3])
cpu
torch.float32


In [8]:
students=torch.tensor([[45.,40.,30.],[4.,5.,6.]])
print(students)

tensor([[45., 40., 30.],
        [ 4.,  5.,  6.]])


In [9]:
avg=students.mean()
print(avg)
avg1=students.mean(dim=0)
print(avg)
avg2=students.mean(dim=1)
print(avg2)

tensor(21.6667)
tensor(21.6667)
tensor([38.3333,  5.0000])


In [10]:
best_student=students.argmax(dim=1)
print(best_student)

tensor([0, 2])


In [3]:
data=torch.tensor([
    [10,11,12,13],
    [20,21,22,23],
    [30,31,32,33]   
])
indices_to_select=torch.tensor([[2],[0],[3]])
selected_students=torch.gather(data,dim=1,index=indices_to_select)
print(selected_students)

tensor([[12],
        [20],
        [33]])


In [4]:
#forward pass
N=10
D_in=1
D_out=1
x=torch.randn(N,D_in)

In [5]:
true_w=torch.tensor([[2.0]])
true_b=torch.tensor(1.0)
print(true_w, true_b)
y_true=x@true_w+true_b+torch.randn(N,D_out)*0.1

tensor([[2.]]) tensor(1.)


In [6]:
w=torch.randn(D_in,D_out,requires_grad=True)
b=torch.randn(1,requires_grad=True)
print(w,b)
y_hat=x@w+b
print(y_hat)

tensor([[0.3206]], requires_grad=True) tensor([0.7059], requires_grad=True)
tensor([[0.6684],
        [0.2234],
        [0.7113],
        [1.0396],
        [0.3410],
        [0.9954],
        [0.6104],
        [1.0000],
        [0.4706],
        [0.2849]], grad_fn=<AddBackward0>)


In [7]:
#backward pass
error=y_hat-y_true
mse=error**2
loss=mse.mean()
print(loss)


tensor(2.3860, grad_fn=<MeanBackward0>)


In [8]:
loss.backward()

# print(f"Gradient for w: {w.grad}")
# print(f"Gradient for b: {b.grad}")


In [25]:
#update parameters
with torch.no_grad():
    learning_rate=0.01
    w-=learning_rate*w.grad
    b-=learning_rate*b.grad
    w.grad.zero_()
    b.grad.zero_()
    print(w,b)
    epochs=100
for epoch in range(epochs):
    y_hat=x@w+b
    error=y_hat-y_true
    mse=error**2
    loss=mse.mean()
    loss.backward()
if loss.item()<0.01:
        print("Training complete")
        print(f"Final loss: {loss.item()}")
print(f"Final weights: {w}")
print(f"Final bias: {b}")

tensor([[2.0200]], requires_grad=True) tensor([0.9494], requires_grad=True)
Training complete
Final loss: 0.008107991889119148
Final weights: tensor([[2.0200]], requires_grad=True)
Final bias: tensor([0.9494], requires_grad=True)
