In [2]:
import torch

In [3]:
data=[[1,2],[3,4]]
data1=torch.tensor(data)
print(data1)

tensor([[1, 2],
        [3, 4]])


In [5]:
shape=(2,3)
ones=torch.ones(shape)
zeros=torch.zeros(shape)
random=torch.tensor(shape)
print(ones)
print(zeros)
print(random)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([2, 3])


In [10]:
copy=torch.randn_like(data1,dtype=torch.float)
print(copy)

tensor([[ 0.0707, -0.3619],
        [-0.3438,  0.5213]])


In [11]:
tensor=torch.rand(2,3)
print(tensor.shape)
print(tensor.device)
print(tensor.dtype)

torch.Size([2, 3])
cpu
torch.float32


In [9]:
students=torch.tensor([[45.,40.,30.],[4.,5.,6.]])
print(students)

tensor([[45., 40., 30.],
        [ 4.,  5.,  6.]])


In [13]:
avg=students.mean()
print(avg)
avg1=students.mean(dim=0)
print(avg)
avg2=students.mean(dim=1)
print(avg2)

tensor(21.6667)
tensor(21.6667)
tensor([38.3333,  5.0000])


In [14]:
best_student=students.argmax(dim=1)
print(best_student)

tensor([0, 2])


In [17]:
data=torch.tensor([
    [10,11,12,13],
    [20,21,22,23],
    [30,31,32,33]   
])
indices_to_select=torch.tensor([[2],[0],[3]])
selected_students=torch.gather(data,dim=1,index=indices_to_select)
print(selected_students)

tensor([[12],
        [20],
        [33]])
