In [1]:
import torch

In [4]:
data=[[1,2],[3,4]]
data1=torch.tensor(data)
print(data1)

tensor([[1, 2],
        [3, 4]])


In [5]:
shape=(2,3)
ones=torch.ones(shape)
zeros=torch.zeros(shape)
random=torch.tensor(shape)
print(ones)
print(zeros)
print(random)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([2, 3])


In [6]:
copy=torch.randn_like(data1,dtype=torch.float)
print(copy)

tensor([[ 0.7766, -0.1226],
        [ 0.7101,  0.4262]])


In [7]:
tensor=torch.rand(2,3)
print(tensor.shape)
print(tensor.device)
print(tensor.dtype)

torch.Size([2, 3])
cpu
torch.float32


In [8]:
students=torch.tensor([[45.,40.,30.],[4.,5.,6.]])
print(students)

tensor([[45., 40., 30.],
        [ 4.,  5.,  6.]])


In [9]:
avg=students.mean()
print(avg)
avg1=students.mean(dim=0)
print(avg)
avg2=students.mean(dim=1)
print(avg2)

tensor(21.6667)
tensor(21.6667)
tensor([38.3333,  5.0000])


In [10]:
best_student=students.argmax(dim=1)
print(best_student)

tensor([0, 2])


In [2]:
data=torch.tensor([
    [10,11,12,13],
    [20,21,22,23],
    [30,31,32,33]   
])
indices_to_select=torch.tensor([[2],[0],[3]])
selected_students=torch.gather(data,dim=1,index=indices_to_select)
print(selected_students)

tensor([[12],
        [20],
        [33]])


In [3]:
#forward pass
N=10
D_in=1
D_out=1
x=torch.randn(N,D_in)

In [4]:
true_w=torch.tensor([[2.0]])
true_b=torch.tensor(1.0)
print(true_w, true_b)
y_true=x@true_w+true_b+torch.randn(N,D_out)*0.1

tensor([[2.]]) tensor(1.)


In [5]:
w=torch.randn(D_in,D_out,requires_grad=True)
b=torch.randn(1,requires_grad=True)
print(w,b)
y_hat=x@w+b
print(y_hat)

tensor([[0.4104]], requires_grad=True) tensor([0.5742], requires_grad=True)
tensor([[ 0.8797],
        [ 0.8251],
        [ 0.3030],
        [ 1.1276],
        [ 0.3800],
        [ 0.5932],
        [ 0.8212],
        [ 0.4478],
        [ 0.0879],
        [-0.0277]], grad_fn=<AddBackward0>)


In [6]:
#backward pass
error=y_hat-y_true
mse=error**2
loss=mse.mean()
print(loss)


tensor(1.9576, grad_fn=<MeanBackward0>)


In [7]:
loss.backward()

# print(f"Gradient for w: {w.grad}")
# print(f"Gradient for b: {b.grad}")


In [8]:
#update parameters
with torch.no_grad():
    learning_rate=0.01
    w-=learning_rate*w.grad
    b-=learning_rate*b.grad
    w.grad.zero_()
    b.grad.zero_()
    print(w,b)
    epochs=100
for epoch in range(epochs):
    y_hat=x@w+b
    error=y_hat-y_true
    mse=error**2
    loss=mse.mean()
    loss.backward()
if loss.item()<0.01:
        print("Training complete")
        print(f"Final loss: {loss.item()}")
print(f"Final weights: {w}")
print(f"Final bias: {b}")

tensor([[0.4334]], requires_grad=True) tensor([0.5799], requires_grad=True)
Final weights: tensor([[0.4334]], requires_grad=True)
Final bias: tensor([0.5799], requires_grad=True)


In [9]:
#Linear.nn module
D_in=1
D_out=1

linear_layer=torch.nn.Linear(in_features=D_in,out_features=D_out)
print(linear_layer.weight)
print(linear_layer.bias)

y_hat_nn=linear_layer(x)
print(y_hat_nn)

Parameter containing:
tensor([[-0.6212]], requires_grad=True)
Parameter containing:
tensor([0.9770], requires_grad=True)
tensor([[0.5145],
        [0.5972],
        [1.3874],
        [0.1394],
        [1.2709],
        [0.9482],
        [0.6031],
        [1.1682],
        [1.7131],
        [1.8880]], grad_fn=<AddmmBackward0>)
